
package grafica;


public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastrarCliente = new javax.swing.JButton();
        ProdutosEstoque = new javax.swing.JButton();
        TodosOsProdutos = new javax.swing.JButton();
        ClientesAtivos = new javax.swing.JButton();
        ProdutosIndisponiveis = new javax.swing.JButton();
        CadastrarProduto = new javax.swing.JToggleButton();
        TodosClientes = new javax.swing.JButton();
        TodasVendas = new javax.swing.JButton();
        CadastrarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Padaria");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximizedBounds(new java.awt.Rectangle(638, 405, 638, 405));
        setResizable(false);

        CadastrarCliente.setText("Cadastrar cliente");
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });

        ProdutosEstoque.setText("Produtos disponiveis");
        ProdutosEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosEstoqueActionPerformed(evt);
            }
        });

        TodosOsProdutos.setText("Todos os produtos cadastrados");
        TodosOsProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosOsProdutosActionPerformed(evt);
            }
        });

        ClientesAtivos.setText("Clientes ativos");
        ClientesAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesAtivosActionPerformed(evt);
            }
        });

        ProdutosIndisponiveis.setText("Produtos Indisponiveis");
        ProdutosIndisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosIndisponiveisActionPerformed(evt);
            }
        });

        CadastrarProduto.setText("Cadastrar produto");
        CadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoActionPerformed(evt);
            }
        });

        TodosClientes.setText("Todos os clientes");
        TodosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosClientesActionPerformed(evt);
            }
        });

        TodasVendas.setText("Todas as vendas");
        TodasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodasVendasActionPerformed(evt);
            }
        });

        CadastrarVenda.setText("Cadastrar venda");
        CadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TodosOsProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdutosEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClientesAtivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TodosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProdutosIndisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(CadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(TodasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TodosOsProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(TodosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdutosEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientesAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProdutosIndisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TodasVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CadastrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
        dispose();
        CadastrarCliente cc = new CadastrarCliente();
        cc.setVisible(true);
        cc.setLocationRelativeTo(null);
    }//GEN-LAST:event_CadastrarClienteActionPerformed

    private void ProdutosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosEstoqueActionPerformed
        dispose();
        ProdutosDisponiveis pe = new ProdutosDisponiveis();
        pe.setVisible(true);
        pe.setLocationRelativeTo(null);
    }//GEN-LAST:event_ProdutosEstoqueActionPerformed

    private void TodosOsProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosOsProdutosActionPerformed
        dispose();
        TodosProdutos tp = new TodosProdutos();
        tp.setVisible(true);
        tp.setLocationRelativeTo(null);
    }//GEN-LAST:event_TodosOsProdutosActionPerformed

    private void ClientesAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesAtivosActionPerformed
        dispose();
        ClientesAtivos lc = new ClientesAtivos();
        lc.setVisible(true);
        lc.setLocationRelativeTo(null);
    }//GEN-LAST:event_ClientesAtivosActionPerformed

    private void ProdutosIndisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosIndisponiveisActionPerformed
        dispose();
        ProdutosIndisponiveis pi = new ProdutosIndisponiveis();
        pi.setVisible(true);
        pi.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_ProdutosIndisponiveisActionPerformed

    private void TodosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosClientesActionPerformed
        // TODO add your handling code here:
        dispose();
        TodosClientes ca = new TodosClientes();
        ca.setVisible(true);
        ca.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_TodosClientesActionPerformed

    private void TodasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodasVendasActionPerformed
        // TODO add your handling code here:
        dispose();
        TodasVendas tv = new TodasVendas();
        tv.setVisible(true);
        tv.setLocationRelativeTo(null);
    }//GEN-LAST:event_TodasVendasActionPerformed

    private void CadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarVendaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CadastrarVendaActionPerformed

    private void CadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastrarProduto cv = new CadastrarProduto();
        cv.setVisible(true);
        cv.setLocationRelativeTo(null);
    }//GEN-LAST:event_CadastrarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarCliente;
    private javax.swing.JToggleButton CadastrarProduto;
    private javax.swing.JButton CadastrarVenda;
    private javax.swing.JButton ClientesAtivos;
    private javax.swing.JButton ProdutosEstoque;
    private javax.swing.JButton ProdutosIndisponiveis;
    private javax.swing.JButton TodasVendas;
    private javax.swing.JButton TodosClientes;
    private javax.swing.JButton TodosOsProdutos;
    // End of variables declaration//GEN-END:variables
}
